In [1]:
import pandas as pd
import numpy as np
import os

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
file_path = "../data/online_retail_II.xlsx"

# Load Sheet 1 and save as CSV
df_sheet1 = pd.read_excel(file_path, sheet_name=0)
df_sheet1.to_csv("../data/sheet1.csv", index=False)

# Load Sheet 2 and save as CSV
df_sheet2 = pd.read_excel(file_path, sheet_name=1)
df_sheet2.to_csv("../data/sheet2.csv", index=False)

df1 = pd.read_csv("../data/sheet1.csv")
df2 = pd.read_csv("../data/sheet2.csv")

In [3]:
df = pd.concat([df1, df2], ignore_index=True)

In [4]:
display(df.head())

print("\n--- DATA TYPES & MISSING VALUES ---")
df.info()

print("\n--- SUMMARY STATISTICS ---")
display(df.describe(include='all'))

print(f"\nMissing Values:\n{df.isnull().sum()}")
print(f"\nDuplicate Rows: {df.duplicated().sum()}")

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

--- DATA TYPES & MISSING VALUES ---
<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  str
 1   StockCode    1067371 non-null  str
 2   Description  1062989 non-null  str
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  str
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 136.6 MB

--- SUMMARY STATISTICS ---

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
count,1067371,1067371,1062989,1.067371e+06,1067371,1.067371e+06,824364.000000,1067371
unique,53628,5305,5698,NaN,47635,NaN,NaN,43
top,537434,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,2010-12-06 16:57:00,NaN,NaN,United Kingdom
freq,1350,5829,5918,NaN,1350,NaN,NaN,981330
mean,NaN,NaN,NaN,9.938898e+00,NaN,4.649388e+00,15324.638504,NaN
std,NaN,NaN,NaN,1.727058e+02,NaN,1.235531e+02,1697.464450,NaN
min,NaN,NaN,NaN,-8.099500e+04,NaN,-5.359436e+04,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000e+00,NaN,1.250000e+00,13975.000000,NaN
50%,NaN,NaN,NaN,3.000000e+00,NaN,2.100000e+00,15255.000000,NaN
75%,NaN,NaN,NaN,1.000000e+01,NaN,4.150000e+00,16797.000000,NaN
max,NaN,NaN,NaN,8.099500e+04,NaN,3.897000e+04,18287.000000,NaN

Missing Values:
Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

Duplicate Rows: 34335

In [5]:

df.rename(columns={
    "Invoice": "InvoiceNo",
    "Customer ID": "CustomerID",
    "Price": "UnitPrice"
}, inplace=True)


df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

df = df[
    (~df["InvoiceNo"].astype(str).str.startswith("C")) &  
    (df["Quantity"] > 0) &                               
    (df["UnitPrice"] > 0)                                
].dropna(subset=["Description", "CustomerID"]).drop_duplicates()  


df["TotalSales"] = df["Quantity"] * df["UnitPrice"]
df["Year"] = df["InvoiceDate"].dt.year
df["Month"] = df["InvoiceDate"].dt.month
df["MonthName"] = df["InvoiceDate"].dt.month_name()
df["Quarter"] = df["InvoiceDate"].dt.quarter
df["Week"] = df["InvoiceDate"].dt.isocalendar().week
df["Day"] = df["InvoiceDate"].dt.day
df["DayName"] = df["InvoiceDate"].dt.day_name()
df["Hour"] = df["InvoiceDate"].dt.hour
df["Weekend"] = df["DayName"].isin(["Saturday", "Sunday"])

print(f"Cleaning & Feature Engineering Complete. Final Shape: {df.shape}")

Cleaning & Feature Engineering Complete. Final Shape: (779425, 18)

In [6]:

os.makedirs("../outputs", exist_ok=True)

# Save cleaned file
#output_path = "../outputs/cleaned_retail.csv"
#df.to_csv(output_path, index=False)

# print("Cleaning Completed Successfully!")
# print(f"File saved at: {output_path}")
display(df.head())

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalSales,Year,Month,MonthName,Quarter,Week,Day,DayName,Hour,Weekend
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009,12,December,4,49,1,Tuesday,7,False
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,December,4,49,1,Tuesday,7,False
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,December,4,49,1,Tuesday,7,False
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009,12,December,4,49,1,Tuesday,7,False
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009,12,December,4,49,1,Tuesday,7,False